title: standing next to me
author: Marcus
description: a blog
url: https://standingnexttome.github.io

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - mise.toml
  - .idea
